version: '3.4'
services:
  rasa:
    image: rasa-ilearn-server-okteto:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
      - ./actions:/app/actions
      - ./data:/app/data
      - ./models:/app/models
    command: bash -c "rm -rf models/* && rm -rf .rasa/* && rasa train && rasa run --enable-api --cors \"*\" -p 8080 --debug"
    ports:
      - '5005:8080' #external:internal
    networks:
      - all

  rasa-actions:
    image: rasa-ilearn-server-okteto:latest
    working_dir: /app
    build: './'
    restart: always
    volumes:
    - ./actions:/app/actions
    ports:
    - '5055:5055'
    command: bash -c "rasa run actions"
    networks:
      - all

  db:
    container_name: postgres_demo
    image: postgres:latest
    environment:
      POSTGRES_USER: chatbox
      POSTGRES_PASSWORD: rasa-chatbox
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"

volumes:
  postgres-db:
    driver: local

